"""initial_schema

Revision ID: 78202507947a
Revises: 
Create Date: 2026-02-01 15:18:12.843212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '78202507947a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_deal_id'), 'analyses', ['deal_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('property_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('zip_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('county', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submarket', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('year_renovated', sa.Integer(), nullable=True),
    sa.Column('num_units', sa.Integer(), nullable=True),
    sa.Column('num_buildings', sa.Integer(), nullable=True),
    sa.Column('num_floors', sa.Integer(), nullable=True),
    sa.Column('square_feet', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('land_area_acres', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('parking_spaces', sa.Integer(), nullable=True),
    sa.Column('unit_mix', sa.JSON(), nullable=True),
    sa.Column('current_noi', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('proforma_noi', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('occupancy_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_rent_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_rent_per_sf', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('valuation', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('price_per_unit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_per_sf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cap_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('property_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_city'), 'assets', ['city'], unique=False)
    op.create_index(op.f('ix_assets_deal_id'), 'assets', ['deal_id'], unique=False)
    op.create_index(op.f('ix_assets_state'), 'assets', ['state'], unique=False)
    op.create_table('assumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('assumption_set_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('acquisition_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('closing_costs_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('loan_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ltv', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('loan_term_years', sa.Integer(), nullable=True),
    sa.Column('amortization_years', sa.Integer(), nullable=True),
    sa.Column('io_period_years', sa.Integer(), nullable=True),
    sa.Column('exit_cap_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('hold_period_years', sa.Integer(), nullable=False),
    sa.Column('selling_costs_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rent_growth_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('expense_growth_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('vacancy_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('capex_reserve_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('capex_reserve_per_sf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('custom_assumptions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assumptions_deal_id'), 'assumptions', ['deal_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('changes_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_deal_id'), 'audit_logs', ['deal_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('cashflow_projections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_exit_year', sa.Boolean(), nullable=False),
    sa.Column('gross_potential_rent', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vacancy_loss', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('other_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('effective_gross_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('operating_expenses', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('noi', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('capex', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('capex_reserve', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('interest_payment', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('principal_payment', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_debt_service', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cash_flow_before_debt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cash_flow_after_debt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('selling_costs', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('loan_payoff', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_sale_proceeds', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_cash_flow', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cumulative_cash_flow', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cash_on_cash', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('dscr', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashflow_projections_model_id'), 'cashflow_projections', ['model_id'], unique=False)
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_deal_id'), 'chat_history', ['deal_id'], unique=False)
    op.create_index(op.f('ix_chat_history_session_id'), 'chat_history', ['session_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tool_call_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    op.create_table('chat_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('langgraph_thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_step', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state_snapshot', sa.JSON(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_threads_deal_id'), 'chat_threads', ['deal_id'], unique=False)
    op.create_index(op.f('ix_chat_threads_langgraph_thread_id'), 'chat_threads', ['langgraph_thread_id'], unique=False)
    op.create_index(op.f('ix_chat_threads_user_id'), 'chat_threads', ['user_id'], unique=False)
    op.create_table('comps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('property_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asset_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('price_per_sf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_per_unit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cap_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('num_units', sa.Integer(), nullable=True),
    sa.Column('square_feet', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comps_deal_id'), 'comps', ['deal_id'], unique=False)
    op.create_table('deal_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_approve', sa.Boolean(), nullable=False),
    sa.Column('can_export', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_team_deal_id'), 'deal_team', ['deal_id'], unique=False)
    op.create_index(op.f('ix_deal_team_user_id'), 'deal_team', ['user_id'], unique=False)
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('deal_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('target_irr', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_close_date', sa.Date(), nullable=True),
    sa.Column('actual_close_date', sa.Date(), nullable=True),
    sa.Column('market', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_name'), 'deals', ['name'], unique=False)
    op.create_index(op.f('ix_deals_user_id'), 'deals', ['user_id'], unique=False)
    op.create_table('deck_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('version_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('pptx_s3_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pdf_s3_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slide_count', sa.Integer(), nullable=True),
    sa.Column('slide_contents', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deck_versions_deal_id'), 'deck_versions', ['deal_id'], unique=False)
    op.create_index(op.f('ix_deck_versions_model_id'), 'deck_versions', ['model_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('s3_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('s3_bucket', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('doc_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('doc_subcategory', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('processing_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('processing_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('extracted_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_asset_id'), 'documents', ['asset_id'], unique=False)
    op.create_index(op.f('ix_documents_deal_id'), 'documents', ['deal_id'], unique=False)
    op.create_table('financial_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('assumption_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('excel_s3_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('irr', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('equity_multiple', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('npv', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cash_on_cash_y1', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('avg_cash_on_cash', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('total_equity', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_investment', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('annual_cashflows', sa.JSON(), nullable=True),
    sa.Column('sensitivity_matrix', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_models_assumption_id'), 'financial_models', ['assumption_id'], unique=False)
    op.create_index(op.f('ix_financial_models_deal_id'), 'financial_models', ['deal_id'], unique=False)
    op.create_table('loan_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('lender_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lender_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('loan_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ltv', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('dscr', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rate_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('spread', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('index', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rate_floor', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('rate_cap', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('loan_term_years', sa.Integer(), nullable=True),
    sa.Column('amortization_years', sa.Integer(), nullable=True),
    sa.Column('io_period_months', sa.Integer(), nullable=True),
    sa.Column('prepayment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prepayment_terms', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lockout_months', sa.Integer(), nullable=True),
    sa.Column('origination_fee_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('exit_fee_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('quote_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('terms_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_quotes_deal_id'), 'loan_quotes', ['deal_id'], unique=False)
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('market', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submarket', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asset_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('property_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_report', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_data_deal_id'), 'market_data', ['deal_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_deal_id'), 'notifications', ['deal_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('operating_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('gross_potential_rent', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('loss_to_lease', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vacancy_loss', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('concessions', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bad_debt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_rental_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('utility_reimbursement', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('parking_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('laundry_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pet_fees', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('other_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_other_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('effective_gross_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('payroll', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('repairs_maintenance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('utilities', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('insurance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('real_estate_taxes', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('management_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('marketing', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('admin_general', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('contract_services', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('other_expenses', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_operating_expenses', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('noi', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('capex', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('debt_service', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cash_flow', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('noi_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('noi_per_sf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expense_ratio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('line_items', sa.JSON(), nullable=True),
    sa.Column('source_doc_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operating_statements_asset_id'), 'operating_statements', ['asset_id'], unique=False)
    op.create_table('rent_rolls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('square_feet', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('market_rent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_rent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rent_per_sf', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('concessions', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tenant_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lease_start', sa.Date(), nullable=True),
    sa.Column('lease_end', sa.Date(), nullable=True),
    sa.Column('move_in_date', sa.Date(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_mtm', sa.Boolean(), nullable=False),
    sa.Column('other_income', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('source_doc_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rent_rolls_asset_id'), 'rent_rolls', ['asset_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('base_model_id', sa.Integer(), nullable=False),
    sa.Column('scenario_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scenario_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parameter_changes', sa.JSON(), nullable=True),
    sa.Column('irr', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('equity_multiple', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('npv', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('irr_delta', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_base_model_id'), 'scenarios', ['base_model_id'], unique=False)
    op.create_index(op.f('ix_scenarios_deal_id'), 'scenarios', ['deal_id'], unique=False)
    op.create_table('sensitivity_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('analysis_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output_metric', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variable_x', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variable_x_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('values_x', sa.JSON(), nullable=True),
    sa.Column('variable_y', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variable_y_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('values_y', sa.JSON(), nullable=True),
    sa.Column('matrix_data', sa.JSON(), nullable=True),
    sa.Column('base_case_x_index', sa.Integer(), nullable=True),
    sa.Column('base_case_y_index', sa.Integer(), nullable=True),
    sa.Column('base_case_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensitivity_analyses_model_id'), 'sensitivity_analyses', ['model_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('s3_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('asset_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deal_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lease_start', sa.Date(), nullable=True),
    sa.Column('lease_end', sa.Date(), nullable=True),
    sa.Column('current_rent', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('market_rent', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('area_sqft', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rent_per_sqft', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lease_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_asset_id'), 'tenants', ['asset_id'], unique=False)
    op.create_index(op.f('ix_tenants_deal_id'), 'tenants', ['deal_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_deal_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_asset_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('templates')
    op.drop_index(op.f('ix_sensitivity_analyses_model_id'), table_name='sensitivity_analyses')
    op.drop_table('sensitivity_analyses')
    op.drop_index(op.f('ix_scenarios_deal_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_base_model_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_rent_rolls_asset_id'), table_name='rent_rolls')
    op.drop_table('rent_rolls')
    op.drop_index(op.f('ix_operating_statements_asset_id'), table_name='operating_statements')
    op.drop_table('operating_statements')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_deal_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_market_data_deal_id'), table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('ix_loan_quotes_deal_id'), table_name='loan_quotes')
    op.drop_table('loan_quotes')
    op.drop_index(op.f('ix_financial_models_deal_id'), table_name='financial_models')
    op.drop_index(op.f('ix_financial_models_assumption_id'), table_name='financial_models')
    op.drop_table('financial_models')
    op.drop_index(op.f('ix_documents_deal_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_asset_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_deck_versions_model_id'), table_name='deck_versions')
    op.drop_index(op.f('ix_deck_versions_deal_id'), table_name='deck_versions')
    op.drop_table('deck_versions')
    op.drop_index(op.f('ix_deals_user_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_name'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_deal_team_user_id'), table_name='deal_team')
    op.drop_index(op.f('ix_deal_team_deal_id'), table_name='deal_team')
    op.drop_table('deal_team')
    op.drop_index(op.f('ix_comps_deal_id'), table_name='comps')
    op.drop_table('comps')
    op.drop_index(op.f('ix_chat_threads_user_id'), table_name='chat_threads')
    op.drop_index(op.f('ix_chat_threads_langgraph_thread_id'), table_name='chat_threads')
    op.drop_index(op.f('ix_chat_threads_deal_id'), table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_history_session_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_deal_id'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_cashflow_projections_model_id'), table_name='cashflow_projections')
    op.drop_table('cashflow_projections')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_deal_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assumptions_deal_id'), table_name='assumptions')
    op.drop_table('assumptions')
    op.drop_index(op.f('ix_assets_state'), table_name='assets')
    op.drop_index(op.f('ix_assets_deal_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_city'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_analyses_deal_id'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
